name: Refresh geojson files and regenerate HTML

on:
  schedule:
    - cron:  '27 * * * *'

jobs:
  refreshscriptt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install osmtogeojson
      run: npm install -g osmtogeojson

    - name: Call the automate.sh script
      run: bash automate.sh

    - name: Push to remote
      run: |
        git config --global user.name "github-actions[bot]"
        git add data
        git add html
        git commit -m "Update geojson files (actions)"
        git push
